In [5]:
%matplotlib inline
import numpy as np
from scipy.optimize import minimize
import matplotlib.pyplot as plt

In [38]:
def simplex_optimization2(x):
    return sum(x[:-1]**2.0)
for d in [2,10,1000] :
    x0 = np.random.randint(-10, high = 10, size = d + 1)
    print(x0)
    res = minimize(simplex_optimization2, x0, method='nelder-mead', options={'xatol': 1e-4, 'disp': True, 'maxfev' : d})
    print(res.x)

[-3  5  3]
[-3.  5.  3.]
[-4  7  1 -6 -9 -1 -9  5  7  1  0]
[-4.  7.  1. -6. -9. -1. -9.  5.  7.  1.  0.]
[ 9 -5 -4 ...  1  2 -5]
[ 9. -5. -4. ...  1.  2. -5.]


In [39]:
def simplex_optimization2(x):
    return sum(100.0*(x[1:]-x[:-1]**2.0)**2.0 + (x[:-1] - 1)**2.0)
for d in [2,10,1000] :
    x0 = np.random.randint(-5, high = 10, size = d + 1)
    res = minimize(simplex_optimization2, x0, method='nelder-mead', options={'xatol': 1e-4, 'disp': True, 'maxfev' : d - 1})
    print(res.x)
    

[-3.    1.05  4.  ]
[ 5.   2.1  6.   4.   2.   6.  -1.  -2.   2.   0.  -1. ]
[ 5. -1.  1. ...  1. -2.  0.]
